name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Run tests
        run: go test -v ./...

      - name: Get version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build binaries
        run: |
          # macOS (Intel)
          GOOS=darwin GOARCH=amd64 go build -ldflags "-s -w" -o tavernshell-darwin-amd64 ./cmd/tavernshell
          
          # macOS (Apple Silicon)
          GOOS=darwin GOARCH=arm64 go build -ldflags "-s -w" -o tavernshell-darwin-arm64 ./cmd/tavernshell
          
          # Linux (amd64)
          GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o tavernshell-linux-amd64 ./cmd/tavernshell
          
          # Linux (arm64) - for Raspberry Pi, etc.
          GOOS=linux GOARCH=arm64 go build -ldflags "-s -w" -o tavernshell-linux-arm64 ./cmd/tavernshell
          
          # Windows (amd64)
          GOOS=windows GOARCH=amd64 go build -ldflags "-s -w" -o tavernshell-windows-amd64.exe ./cmd/tavernshell

      - name: Generate checksums
        run: |
          sha256sum tavernshell-* > checksums.txt
          cat checksums.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            tavernshell-darwin-amd64
            tavernshell-darwin-arm64
            tavernshell-linux-amd64
            tavernshell-linux-arm64
            tavernshell-windows-amd64.exe
            checksums.txt
          generate_release_notes: true
          draft: false
          prerelease: false

